---
- name: add ppa
  apt_repository:
    repo: ppa:jtaylor/keepass
    state: present
    update_cache: yes
  become: yes

- name: instal
  apt:
    name: keepass2
    state: present
    update_cache: yes
  become: yes
