---
- name: Download Vagrant
  get_url:
    url: https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_{{ vagrant_arch }}.deb
    dest: /tmp/vagrant_{{ vagrant_version }}_{{ vagrant_arch }}.deb

- name: Install Vagrant
  apt:
    deb: /tmp/vagrant_{{ vagrant_version }}_{{ vagrant_arch }}.deb
    state: installed
  become: yes
