---
- name: (Debian) download atom
  get_url: >-
    url={{ atom_deb_url }}
    dest=/tmp/{{atom_deb}}
    owner=root
    group=root
    mode=0644

- name: (Debian) install atom
  apt: deb='/tmp/{{ atom_deb }}'
