- apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
  become: yes

- apt_repository:
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: 'google-chrome-stable'
    update_cache: yes
  become: yes

- name: install
  apt:
    name: google-chrome-stable
    state: present
  become: yes
