---
- name: check if Terminator is installed
  shell: dpkg -l | grep -E '^ii' | grep terminator
  register: terminator_installed
  ignore_errors: yes

- name: install Terminator
  apt:
    name: "terminator"
    state: installed
  when: terminator_installed.rc != 0
