- apt_key:
    url: https://repo.yandex.ru/yandex-browser/YANDEX-BROWSER-KEY.GPG
    state: present
  become: yes

- apt_repository:
    repo: deb https://repo.yandex.ru/yandex-browser/deb beta main
    state: present
    filename: 'yandex-browser-beta'
    update_cache: yes
  become: yes

- name: install
  apt:
    name: yandex-browser-beta
    state: present
    update_cache: yes
  become: yes
